apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "opendata-map.fullname" . }}-nginx"
  labels:
    {{- include "opendata-map.labels" . | nindent 4 }}
data:
  {{- range .Values.nginx.templates }}
  {{- .name | nindent 2 }}: >
    {{- .config | nindent 4 }}
  {{- end }}
