apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "opendata-map.fullname" . }}"
  labels:
    {{- include "opendata-map.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.dotEnv | nindent 2 }}
