{{- if not .Values.persistentVolume.existingClaim.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opendata-map.fullname" . }}-pv-claim
spec:
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
{{- end }}

---
{{- if not .Values.openstreetmap.persistentVolume.db.existingClaim.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opendata-map.fullname" . }}-pv-map-db-claim
spec:
  storageClassName: {{ .Values.openstreetmap.persistentVolume.db.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.openstreetmap.persistentVolume.db.size }}
{{- end }}

---
{{- if not .Values.openstreetmap.persistentVolume.tileCache.existingClaim.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opendata-map.fullname" . }}-pv-map-tile-cache-claim
spec:
  storageClassName: {{ .Values.openstreetmap.persistentVolume.tileCache.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.openstreetmap.persistentVolume.tileCache.size }}
{{- end }}

---
{{- if and .Values.openstreetmap.init.enabled (and .Values.openstreetmap.init.persistentVolume.importData.enabled (not .Values.openstreetmap.init.persistentVolume.importData.existingClaim.enable)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opendata-map.fullname" . }}-pv-map-import-data-claim
spec:
  storageClassName: {{ .Values.openstreetmap.persistentVolume.importData.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.openstreetmap.persistentVolume.importData.size }}
{{- end }}

---
{{- if and .Values.openstreetmap.init.enabled (and .Values.openstreetmap.init.persistentVolume.nodeCache.enabled (not .Values.openstreetmap.init.persistentVolume.nodeCache.existingClaim.enable)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opendata-map.fullname" . }}-pv-map-flatnode-cache-claim
spec:
  storageClassName: {{ .Values.openstreetmap.persistentVolume.nodeCache.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.openstreetmap.persistentVolume.nodeCache.size }}
{{- end }}
